/**
 * DEPTH FIRST SEARCH, TOPOLOGICAL ORDERING AND
 * BELLMAN FORD GRAPH ALGORITHMS IMPLEMENTATION
 * 
 * Computer Science Departament of
 * Federal University of Lavras (UFLA)
 * 
 * This project was developed for Design and 
 * Analysis of Algorithms discipline as the
 * main pratical project.
 * 
 * It was developed by:
 * 
 * Lucas Fonseca dos Santos
 * https://github.com/LucasFonsecadosSantos
 * 
 * Marco Aurelio Ferreira de Sousa
 * https://github.com/maureliofs
 * 
 * ~This code can be used for students for
 * to learn more about graphs processing.~
 */
package entity;

/**
 * This abstraction allows the algorithms present
 * in this project, to store a tuple struct, in this
 * case, a time tuple that represents the time assied
 * to each vertex, used for store information about
 * discoverty and finish time generated by Depth
 * First Search algorithm processing and used by
 * Topological Ordering algorithm.
 * 
 * @author Lucas Fonseca dos Santos
 * @author Marco Aurelio Ferreira de Sousa
 * @version 1.0
 * @since 1.0
 */
public class TimeTuple {

    /**
     * The vertex attribute.
     */
    private String vertex;

    /**
     * The time attribute.
     */
    private int time;

    /**
     * The TimeTuple object constructor. It just sets
     * the vertex and time attribbute state.
     * 
     * @param vertex The new vertex attribute state value.
     * @param time The new time attribute state value.
     */
    public TimeTuple(String vertex, int time) {
        setVertex(vertex);
        setTime(time);
    }

    /**
     * Vertex attribute state modifier method.
     * 
     * @param vertex The new vertex attribute state value.
     */
    public void setVertex(String vertex) {
        this.vertex = vertex;
    }

    /**
     * Time attribute state modifier method.
     * 
     * @param time The new integer time attribute state value.
     */
    public void setTime(int time) {
        this.time = time;
    }

    /**
     * Vertex attribute state accessor method.
     * 
     * @return String The string vertex attribute state.
     */
    public String getVertex() {
        return this.vertex;
    }

    /**
     * Time attribute state accessor method.
     * 
     * @return int The integer time attribute state.
     */
    public int getTime() {
        return this.time;
    }
}